# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fib_pair_four_million(n):
    a = 1
    b = 2
    for i in range(1,n+1):
        if a%2 == 0:
            yield a
        if a > 4000000: # fib not exceed four million
            break
        aux = a
        a = b
        b+=aux

print(sum(fib_pair_four_million(4000000)))